---
  - name: backup galera cluster
    mysql_db:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: dump
      name: all
      target: "{{ path_backup }}all_{{ ansible_date_time.date }}.sql"
    tags:
      - backup


  - name: scp backup to nfs server
    shell: "scp  {{ path_backup }}all_{{ ansible_date_time.date }}.sql root@nfs:/storage/glance/{{ dir_mysql_backup }}/"
    tags:
      - backup

      
  - name: scp backup to checkDB server
    shell: "scp {{ path_backup }}all_{{ ansible_date_time.date }}.sql root@checkDB:/home/mua/db_file"
    tags:
      - backup
      - checkDB

  - name: Remove old files backup
    file:
      path: "{{ path_backup }}all_{{ ansible_date_time.date }}.sql"
      state: absent
    tags:
      - backup      

