---

#  - name: backup db
    #become: true
    #become_user: root
    #     shell: mysqldump -u root --single-transaction --all-databases  > /home/all.sql
    #  tags:
    #   - backup

- name: backup galera cluster
  mysql_db:
    state: dump
    name: all
    target: "{{ path_backup }}all_{{ ansible_date_time.date }}.sql"
  become: yes
  become_method: enable
  tags:
    - backup



- name: scp backup to server
  fetch:
    src: "{{ path_backup }}all_{{ ansible_date_time.date }}.sql"
    dest: "{{ backup_storage_path }}all_{{ ansible_date_time.date }}.sql"
    flat: yes
    validate_checksum: no
  tags:
    - backup

- name: Print the gateway for each host when defined
  debug:
    msg: "scp {{ path_backup }}all_{{ ansible_date_time.date }}.sql 172.16.109.9:/storage/glance/backup_mysql_tbz/"
  tags:
    - backup
  
- name: scp backup to nfs server
  shell: "scp {{ path_backup }}all_{{ ansible_date_time.date }}.sql 172.16.109.9:/storage/glance/backup_mysql_tbz/"
  #command: "rsync  -azvP {{ backup_storage_path }}all_{{ ansible_date_time.date }}.sql 172.16.104.9:/storage/glance/backup_mysql_tbz/"
  tags:
    - backup


- name: restart mariadb
  service: name=mysql enabled=yes state=restarted
  tags:
    - mysql_restart

