---


- name: backup galera cluster
  mysql_db:
    state: dump
    name: all
    target: "{{ path_backup }}all_{{ ansible_date_time.date }}.sql"
  tags:
    - backup



- name: scp backup to server
  fetch:
    src: "{{ path_backup }}all_{{ ansible_date_time.date }}.sql"
    dest: "{{ backup_storage_path }}all_{{ ansible_date_time.date }}.sql"
    flat: yes
    validate_checksum: no
  tags:
    - backup

- name: scp backup to nfs server
  shell: "scp {{ path_backup }}all_{{ ansible_date_time.date }}.sql root@nfs:/storage/glance/backup_mysql_tbz/"
  tags:
    - backup

- name: restart mariadb
  service: name=mysql enabled=yes state=restarted
  tags:
    - mysql_restart

