<<<<<<< HEAD
# vim:ft=ansible:


---
- name: check public_key
  stat:
    path: "{{ rsa_pub }}"
  register: available_key
  tags:
    - backup

- name: Task name
  debug:
    msg: "The file or directory exists"
  when: available_key.stat.exists
- name: create public_key
  shell: >
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"
  when: available_key.stat.exists
  tags:
    - backup

- name: check key in nfs for galeracluster
  shell: "cat {{ rsa_pub }}"
  delegate_to: "{{ infra3_galera }}"
  register: out
  tags:
    - backup

- name: variable
  debug:
    var: out.stdout
  tags:
    - backup
- name: add key in nfs server
  delegate_to: "{{ nfs_ip }}"
  lineinfile: 
    dest: "{{ copy_to_nfs }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop  :
    - regexp: "^ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDgvW6e5I9b2Gw9E8m"
      line: "{{ out.stdout }}"
  tags:
    - backup

- name: backup galera cluster
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
=======
---


- name: backup galera cluster
  mysql_db:
>>>>>>> 96fc0e97430f870938b2e7281f2c55b648ca55b8
    state: dump
    name: all
    target: "{{ path_backup }}all_{{ ansible_date_time.date }}.sql"
  tags:
    - backup


<<<<<<< HEAD
- name: scp backup to nfs server
  shell: "scp {{ path_backup }}all_{{ ansible_date_time.date }}.sql root@172.20.4.7:/storage/glance/backup_mysql_beh/"
  tags:
    - backup
=======

- name: scp backup to nfs server
  shell: "scp {{ path_backup }}all_{{ ansible_date_time.date }}.sql root@nfs:/storage/glance/backup_mysql/"
  tags:
    - backup
    
- name: scp backup to checkDB server
  shell: "scp {{ path_backup }}all_{{ ansible_date_time.date }}.sql root@checkDB:/home/mua/db_file"
  tags:
    - backup
    - checkDB
>>>>>>> 96fc0e97430f870938b2e7281f2c55b648ca55b8

- name: restart mariadb
  service: name=mysql enabled=yes state=restarted
  tags:
    - mysql_restart

