---
# handlers file for pre-deploy
- name: restart resolved                                                                                                                                                        
  ansible.builtin.service:                                                                                        
    name: systemd-resolved                                                                                
    state: restarted                                                                                   
