---
# defaults file for pre-deploy

domian_name: "domain"


proxy_url: "http://ip:3128/"

pkgs_remove: ['netplan.io', 'resolvconf', 'cloud-init', 'keepalived', 'haproxy']
pkgs_install: ['ifupdown', 'aptitude', 'bridge-utils', 'debootstrap', 'ifenslave', 'ifenslave-2.6', 'lsof', 'lvm2', 'chrony', 'emacs', 'tcpdump', 'vlan', 'python3', 'nmap', 'fping', 'traceroute', 'nload', 'ethstats', 'iftop', 'htop']

preferred_dns: "8.8.8.8"
fallback_dns: "1.1.1.1"
search_domains: ["domain"]
interfaces:
  - eno1
  - eno2


extlb_vlanID: "12"
storage_vlanID: "4"
vxlan_vlanID: "3"

extlb_NET: "172.20.12"
extlb_CIDR: "24"
extlb_GW: "172.20.12.254"

mgmt_NET: "172.20.8"
mgmt_CIDR: "22"
mgmt_GW: "172.20.11.254"

storage_NET: "172.20.4"
storage_CIDR: "22"

vxlan_NET: "172.20.3"
vxlan_CIDR: "24"
