---
# tasks file for pre-deploy
- name: repo
  template:
    src: apt-list.j2
    dest: /etc/apt/sources.list
  tags:
    - compute
    - apt
    - mon
    - osd
    - ovs

- name: apt update source list
  shell: apt update
  tags:
    - infra
    - compute
    - apt
    - mon
    - osd
    - ovs

- name: Configure /etc/systemd/resolved.conf
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  notify:
  - restart resolved
  tags:
    - infra
    - compute
    - resolved
    - mon
    - osd
    - ovs

- name: Install packages "{{ pkgs_install }}"
  apt:
    name: "{{ pkgs_install }}"
    state: present
  tags:
    - infra
    - compute
    - mon
    - osd



- name: remove packages "{{ pkgs_remove }}"
  apt:
    name: "{{ pkgs_remove }}"
    purge: yes
    state: absent
  tags:
    - infra
    - compute
    - mon
    - osd



- name: Update distro to the latest version
  apt:
    upgrade: dist
  tags:
    - infra
    - compute
    - mon
    - osd
    - ovs

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  tags:
    - infra
    - compute
    - mon
    - osd
    - ovs


- name: Configure /etc/modules file
  copy:
    src: modules
    dest: /etc/modules
  tags:
    - infra
    - compute
    - mon
    - osd
    - ovs

- name: Configure /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags:
    - infra
    - compute
    - ovs

- name: Clean up  /openstack /etc/haproxy /etc/keepalived directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/openstack/"
    - "/etc/haproxy"
    - "/etc/keepalived/"
  tags:
    - infra
    - compute
    - ovs

- name: clean LXC containers
  shell:
    cmd: "x=$(lxc-ls); for i in $x; do lxc-stop $i; lxc-destroy $i; done"
  tags:
    - infra
    - ovs_infra















