---
# tasks file for os_qouta-project

# List a Project Quota
- name: List Quota Project
  os_quota:
<<<<<<< HEAD
#    cloud: "{{ CLOUD_NAME }}"
    name: "{{ item.name }}"
  with_items:
    - "{{ projects }}"

=======
    cloud: "{{ CLOUD_NAME }}"
    name: "{{ project_name }}"
>>>>>>> 824d53c4f04f0332624dff6354028a08dc185355
  register: quota_var
#  tag: list
#quota_var is varible 
- debug: 
    var: quota_var

# Complete example based on list of projects
<<<<<<< HEAD
#- name: Update quotas
#  os_quota:
#    name: "{{ item.name }}"
=======
- name: Update quotas
  os_quota:
    name: "{{ item.name }}"
>>>>>>> 824d53c4f04f0332624dff6354028a08dc185355
#    backup_gigabytes: "{{ item.backup_gigabytes }}"
#    backups: "{{ item.backups }}"
#    cores: "{{ item.cores }}"
#    fixed_ips: "{{ item.fixed_ips }}"
#    floating_ips: "{{ item.floating_ips }}"
#    floatingip: "{{ item.floatingip }}"
#    gigabytes: "{{ item.gigabytes }}"
#    injected_file_size: "{{ item.injected_file_size }}"
#    injected_files: "{{ item.injected_files }}"
#    injected_path_size: "{{ item.injected_path_size }}"
#    instances: "{{ item.instances }}"
#    key_pairs: "{{ item.key_pairs }}"
#    loadbalancer: "{{ item.loadbalancer }}"
#    per_volume_gigabytes: "{{ item.per_volume_gigabytes }}"
#    pool: "{{ item.pool }}"
#    port: "{{ item.port }}"
#    properties: "{{ item.properties }}"
#    ram: "{{ item.ram }}"
#    security_group_rule: "{{ item.security_group_rule }}"
#    security_group: "{{ item.security_group }}"
#    server_group_members: "{{ item.server_group_members }}"
#    server_groups: "{{ item.server_groups }}"
#    snapshots: "{{ item.snapshots }}"
#    volumes: "{{ item.volumes }}"
#    volumes_types:
#      volumes_lvm: "{{ item.volumes_lvm }}"
#    snapshots_types:
#      snapshots_lvm: "{{ item.snapshots_lvm }}"
#    gigabytes_types:
#      gigabytes_lvm: "{{ item.gigabytes_lvm }}"
<<<<<<< HEAD
#  with_items:
#    - "{{ projects }}"
=======
  with_items:
    - "{{ projects }}"
>>>>>>> 824d53c4f04f0332624dff6354028a08dc185355
#  when: item.state == "present"
#  tag: update
