---
- name: copy node_exporter_haproxy in other server
  copy:
    src: "{{ file }}"
    dest: "{{ path }}"
    mode: '0777'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Execute the script
  shell: "{{ path }}{{ file }} &"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: configure haproxy.cfg
  shell: haproxy -f "{{ config_path }}"


