---

- name: restart rabbitmq
  systemd:
    state: restarted
    daemon_reload: true
    name: rabbitmq-server


- name: stop rabbitmq
  systemd:
    state: stopped
    daemon_reload: true
    name: rabbitmq-server

- name: start rabbitmq
  systemd:
    state: started
    daemon_reload: true
    name: rabbitmq-server
