---
# tasks file for os_identity-user
- name: Generate random password
  set_fact:
    user_password: "{{lookup('password', '/dev/null length={{password_lenght}} chars=ascii_letters') }}"
    
- name: Create user {{ user_name }}
  os_user:
    cloud: "{{CLOUD_NAME}}"
    state: present
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    domain: "{{ domain_name }}"

- name: Assign user to specified role in designated environment
  os_user_role:
    cloud: "{{CLOUD_NAME}}"
    user: "{{ user_name }}"
    role: "{{ user_role }}"
    project: "{{ project_name }}"
    
- name: User password assignment
  debug: msg="User (( {{ user_name }} )) was added to (( {{ project_name }} )) project, with the assigned password of {{user_password}}"

- name: Delete user {{ user_name }}
  os_user:
    cloud: "{{CLOUD_NAME}}"
    state: absent
    name: "{{ user_name }}"
    domain: "{{ domain_name }}"
  tags: [ never, del-user ]
  
