---
- name: download journalbeat deb package
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/journalbeat/journalbeat-7.9.2-amd64.deb
    dest: "/root"
    
- name: install journalbeat deb package
  apt: deb="/root/journalbeat-7.9.2-amd64.deb"
 
- name: create config file
  template:
    src: "journalbeat.yaml.j2"
    dest: "/etc/journalbeat/journalbeat.yml"    
       
- name: restart journalbeat service 
  service:
    name: journalbeat
    state: restarted 

